Delete component
dentych/ITTWEB pull request #60
Opened 2016-11-30 21:53 UTC by David176

2016-11-30 21:56 UTC, dentych requested changes

2016-11-30 21:56 UTC, dentych commented on EmbeddedStock/Controllers/ComponentController.cs
> +        public IActionResult Delete_ComponentType(int id)
Det er Component, ikke ComponentType

2016-11-30 21:56 UTC, dentych commented on EmbeddedStock/Controllers/ComponentController.cs
> +            return RedirectToAction("Index");
Component controlleren har ikke en "Index" action..

2016-11-30 22:41 UTC, dentych requested changes
Jeg har fixet dine commits. Controlleren ser fin ud. Hvordan foreslår du man gør brug af controlleren? Der er ingen knap/link eller andet, man kan trykke på, for at slette en component.

2016-12-01 08:39 UTC, Agotado commented on EmbeddedStock/Controllers/ComponentController.cs
> +            return context.Components.Single(ct => ct.ComponentId == id);
måske lidt forvirrende at variablen hedder "ct", det er bare sukker, men det var jo oprindeligt for "componentType"

2016-12-01 08:40 UTC, dentych commented on EmbeddedStock/Controllers/ComponentController.cs
> +            return context.Components.Single(ct => ct.ComponentId == id);
That's kinda true

2016-12-01 08:41 UTC, dentych approved these changes

2016-12-01 08:41 UTC, merged